# Generated by Django 5.2.7 on 2025-10-25 20:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Inbound (Purchase/Addition)'), ('OUT', 'Outbound (Sale/Use)')], default='OUT', max_length=3)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-date_recorded'],
                'indexes': [models.Index(fields=['-date_recorded'], name='partstock_s_date_re_10cb74_idx'), models.Index(fields=['movement_type'], name='partstock_s_movemen_1e57c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price_at_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('unit_cost_at_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_items', to='partstock.part')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partstock.stockmovement')),
            ],
            options={
                'verbose_name': 'Movement Item',
                'verbose_name_plural': 'Movement Items',
            },
        ),
    ]
