# Generated by Django 5.2.7 on 2025-10-28 14:08

from django.db import migrations

TASK_PATH = 'partstock.tasks.replenish_stock_task'
TASK_NAME = 'Replenish Stock Daily'

def create_initial_replenishment_task(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat', 'CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    crontab_schedule, created_schedule = CrontabSchedule.objects.get_or_create(
        minute='0',
        hour='1',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )

    PeriodicTask.objects.update_or_create(
        name=TASK_NAME,
        defaults={
            'crontab': crontab_schedule,
            'task': TASK_PATH,
            'enabled': True,
            'args': '[]',
            'kwargs': '{}',
        }
    )

def remove_initial_replenishment_task(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(name=TASK_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('partstock', '0002_uploadtask')
    ]

    operations = [
        migrations.RunPython(
            create_initial_replenishment_task, 
            reverse_code=remove_initial_replenishment_task
        ),
    ]